"""add venue and product tables

Revision ID: 2052a9c7abfc
Revises: fe76b0b94b53
Create Date: 2026-08-13 19:00:15.288885

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2052a9c7abfc"
down_revision: str | Sequence[str] | None = "fe76b0b94b53"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "venue_categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["venue_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "global_product_types",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["venue_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "venue_category_translations",
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["venue_categories.id"],
        ),
        sa.PrimaryKeyConstraint("category_id", "locale"),
    )
    # geoalchemy2.alembic_helpers registers create_geospatial_table/index
    # and drop_geospatial_table/index on `op` at import time (see
    # migrations/env.py's `writer` wiring) — pyright can't see a
    # runtime-registered attribute, hence the ignores below.
    op.create_geospatial_table(  # pyright: ignore[reportAttributeAccessIssue]
        "venues",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.Column(
            "location",
            Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            sa.Computed(
                "ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography", persisted=True
            ),
            nullable=False,
        ),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('turkish', name)", persisted=True),
            nullable=False,
        ),
        sa.Column("address_note", sa.Text(), nullable=True),
        sa.Column("google_places_id", sa.String(), nullable=True),
        sa.Column("added_by", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("country_code", sa.CHAR(length=2), nullable=True),
        sa.Column("timezone", sa.String(), nullable=True),
        sa.Column("status", sa.String(), server_default="active", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["added_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["venue_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_geospatial_index(  # pyright: ignore[reportAttributeAccessIssue]
        "idx_venues_location",
        "venues",
        ["location"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_table(
        "global_product_type_translations",
        sa.Column("product_type_id", sa.UUID(), nullable=False),
        sa.Column("locale", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_type_id"],
            ["global_product_types.id"],
        ),
        sa.PrimaryKeyConstraint("product_type_id", "locale"),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("venue_id", sa.UUID(), nullable=False),
        sa.Column("global_type_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["global_type_id"],
            ["global_product_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "venue_saves",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("venue_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("venue_saves")
    op.drop_table("products")
    op.drop_table("global_product_type_translations")
    op.drop_geospatial_index(  # pyright: ignore[reportAttributeAccessIssue]
        "idx_venues_location",
        table_name="venues",
        postgresql_using="gist",
        column_name="location",
    )
    op.drop_geospatial_table("venues")  # pyright: ignore[reportAttributeAccessIssue]
    op.drop_table("venue_category_translations")
    op.drop_table("global_product_types")
    op.drop_table("venue_categories")
    # ### end Alembic commands ###
