"""add social graph, visibility, likes, bookmarks, notifications

Revision ID: 5ca483ebec03
Revises: 8ca3e119a6a7
Create Date: 2026-08-18 23:34:57.100972

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ca483ebec03"
down_revision: str | Sequence[str] | None = "8ca3e119a6a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "follows",
        sa.Column("follower_id", sa.UUID(), nullable=False),
        sa.Column("following_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "follower_id != following_id", name="ck_follows_no_self_follow"
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["following_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("follower_id", "following_id"),
    )
    op.create_index(
        op.f("ix_follows_following_id"), "follows", ["following_id"], unique=False
    )
    op.create_table(
        "lists",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("visibility", sa.String(), server_default="public", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "visibility IN ('public', 'close_friends', 'private')",
            name="ck_lists_visibility_allowed",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lists_user_id"), "lists", ["user_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("target_type", sa.String(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False
    )
    op.create_table(
        "close_friends",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("friend_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["friend_id", "user_id"],
            ["follows.follower_id", "follows.following_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "friend_id"),
    )
    op.create_table(
        "list_bookmarks",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("list_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["list_id"], ["lists.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "list_id"),
    )
    op.create_index(
        op.f("ix_list_bookmarks_list_id"), "list_bookmarks", ["list_id"], unique=False
    )
    op.create_table(
        "list_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("list_id", sa.UUID(), nullable=False),
        sa.Column("venue_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.String(collation="C"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["list_id"], ["lists.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("list_id", "venue_id", name="uq_list_items_list_venue"),
    )
    op.create_index(
        "ix_list_items_list_id_position",
        "list_items",
        ["list_id", "position"],
        unique=False,
    )
    op.create_index(
        op.f("ix_list_items_venue_id"), "list_items", ["venue_id"], unique=False
    )
    op.create_table(
        "list_likes",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("list_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["list_id"], ["lists.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "list_id"),
    )
    op.create_index(
        op.f("ix_list_likes_list_id"), "list_likes", ["list_id"], unique=False
    )
    op.create_table(
        "checkin_bookmarks",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("checkin_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["checkin_id"], ["checkins.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "checkin_id"),
    )
    op.create_index(
        op.f("ix_checkin_bookmarks_checkin_id"),
        "checkin_bookmarks",
        ["checkin_id"],
        unique=False,
    )
    op.create_table(
        "checkin_likes",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("checkin_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["checkin_id"], ["checkins.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "checkin_id"),
    )
    op.create_index(
        op.f("ix_checkin_likes_checkin_id"),
        "checkin_likes",
        ["checkin_id"],
        unique=False,
    )
    # Added nullable first so existing rows can be backfilled from their
    # real is_public value (server_default only applies going forward,
    # to rows inserted after this point) — not just defaulted to
    # 'public' and losing what they actually had.
    op.add_column(
        "checkins",
        sa.Column("visibility", sa.String(), server_default="public", nullable=True),
    )
    op.execute(
        "UPDATE checkins SET visibility = CASE WHEN is_public THEN 'public' "
        "ELSE 'private' END"
    )
    op.alter_column("checkins", "visibility", nullable=False)
    op.create_check_constraint(
        "ck_checkins_visibility_allowed",
        "checkins",
        "visibility IN ('public', 'close_friends', 'private')",
    )
    op.drop_column("checkins", "is_public")
    op.add_column(
        "venue_saves",
        sa.Column("visibility", sa.String(), server_default="private", nullable=False),
    )
    op.create_unique_constraint(
        "uq_venue_saves_user_venue_type", "venue_saves", ["user_id", "venue_id", "type"]
    )
    op.create_check_constraint(
        "ck_venue_saves_visibility_allowed",
        "venue_saves",
        "visibility IN ('public', 'close_friends', 'private')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_venue_saves_visibility_allowed", "venue_saves", type_="check"
    )
    op.drop_constraint("uq_venue_saves_user_venue_type", "venue_saves", type_="unique")
    op.drop_column("venue_saves", "visibility")
    # close_friends collapses to is_public=false on downgrade — the
    # closest lossy-but-sensible mapping, since a boolean can't represent
    # the middle tier.
    op.add_column(
        "checkins",
        sa.Column("is_public", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.execute("UPDATE checkins SET is_public = (visibility = 'public')")
    op.alter_column("checkins", "is_public", nullable=False)
    op.drop_constraint("ck_checkins_visibility_allowed", "checkins", type_="check")
    op.drop_column("checkins", "visibility")
    op.drop_index(op.f("ix_checkin_likes_checkin_id"), table_name="checkin_likes")
    op.drop_table("checkin_likes")
    op.drop_index(
        op.f("ix_checkin_bookmarks_checkin_id"), table_name="checkin_bookmarks"
    )
    op.drop_table("checkin_bookmarks")
    op.drop_index(op.f("ix_list_likes_list_id"), table_name="list_likes")
    op.drop_table("list_likes")
    op.drop_index(op.f("ix_list_items_venue_id"), table_name="list_items")
    op.drop_index("ix_list_items_list_id_position", table_name="list_items")
    op.drop_table("list_items")
    op.drop_index(op.f("ix_list_bookmarks_list_id"), table_name="list_bookmarks")
    op.drop_table("list_bookmarks")
    op.drop_table("close_friends")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_lists_user_id"), table_name="lists")
    op.drop_table("lists")
    op.drop_index(op.f("ix_follows_following_id"), table_name="follows")
    op.drop_table("follows")
    # ### end Alembic commands ###
