"""add missing foreign key indexes

Revision ID: 8ca3e119a6a7
Revises: 96accf2c3593
Create Date: 2026-08-18 19:29:33.399142

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ca3e119a6a7"
down_revision: str | Sequence[str] | None = "96accf2c3593"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_global_product_types_category_id"),
        "global_product_types",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_products_global_type_id"), "products", ["global_type_id"], unique=False
    )
    op.create_index(
        op.f("ix_products_venue_id"), "products", ["venue_id"], unique=False
    )
    op.create_index(
        op.f("ix_venue_categories_parent_id"),
        "venue_categories",
        ["parent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_venue_saves_user_id"), "venue_saves", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_venue_saves_venue_id"), "venue_saves", ["venue_id"], unique=False
    )
    op.create_index(op.f("ix_venues_added_by"), "venues", ["added_by"], unique=False)
    op.create_index(
        op.f("ix_venues_category_id"), "venues", ["category_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_venues_category_id"), table_name="venues")
    op.drop_index(op.f("ix_venues_added_by"), table_name="venues")
    op.drop_index(op.f("ix_venue_saves_venue_id"), table_name="venue_saves")
    op.drop_index(op.f("ix_venue_saves_user_id"), table_name="venue_saves")
    op.drop_index(op.f("ix_venue_categories_parent_id"), table_name="venue_categories")
    op.drop_index(op.f("ix_products_venue_id"), table_name="products")
    op.drop_index(op.f("ix_products_global_type_id"), table_name="products")
    op.drop_index(
        op.f("ix_global_product_types_category_id"), table_name="global_product_types"
    )
    # ### end Alembic commands ###
