"""add checkin core loop and user role

Revision ID: 96accf2c3593
Revises: ed402e8663f4
Create Date: 2026-08-18 19:19:16.799907

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96accf2c3593"
down_revision: str | Sequence[str] | None = "ed402e8663f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checkins",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("venue_id", sa.UUID(), nullable=False),
        sa.Column("rating_service", sa.Integer(), nullable=True),
        sa.Column("rating_ambiance", sa.Integer(), nullable=True),
        sa.Column("rating_value", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("photo_url", sa.String(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("visited_at", sa.Date(), nullable=False),
        sa.Column("visited_tz", sa.String(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rating_ambiance IS NULL OR rating_ambiance BETWEEN 1 AND 4",
            name="ck_checkins_rating_ambiance_range",
        ),
        sa.CheckConstraint(
            "rating_service IS NULL OR rating_service BETWEEN 1 AND 4",
            name="ck_checkins_rating_service_range",
        ),
        sa.CheckConstraint(
            "rating_value IS NULL OR rating_value BETWEEN 1 AND 4",
            name="ck_checkins_rating_value_range",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_checkins_user_id"), "checkins", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_checkins_venue_id"), "checkins", ["venue_id"], unique=False
    )
    op.create_table(
        "checkin_products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("checkin_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "rating BETWEEN 1 AND 4", name="ck_checkin_products_rating_range"
        ),
        sa.ForeignKeyConstraint(["checkin_id"], ["checkins.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "checkin_id", "product_id", name="uq_checkin_products_checkin_product"
        ),
    )
    op.create_index(
        op.f("ix_checkin_products_product_id"),
        "checkin_products",
        ["product_id"],
        unique=False,
    )
    op.add_column(
        "users", sa.Column("role", sa.String(), server_default="user", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    op.drop_index(op.f("ix_checkin_products_product_id"), table_name="checkin_products")
    op.drop_table("checkin_products")
    op.drop_index(op.f("ix_checkins_venue_id"), table_name="checkins")
    op.drop_index(op.f("ix_checkins_user_id"), table_name="checkins")
    op.drop_table("checkins")
    # ### end Alembic commands ###
