"""add username change rate-limit timestamp

Records when a user last changed their handle, so the rate limit in
app.services.user has something durable to measure against. Nullable: a
user who has never changed it has nothing to record, which is different
from having changed it long ago.

Revision ID: a29f4e0a038b
Revises: 0c10d9ee531a
Create Date: 2026-08-24 01:52:39.734755

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a29f4e0a038b"
down_revision: str | Sequence[str] | None = "0c10d9ee531a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("username_changed_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "username_changed_at")
    # ### end Alembic commands ###
