"""add venue_saves type check constraint

Revision ID: d13e2095d80e
Revises: 5ca483ebec03
Create Date: 2026-08-18 23:47:41.504339

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d13e2095d80e"
down_revision: str | Sequence[str] | None = "5ca483ebec03"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_venue_saves_type_allowed",
        "venue_saves",
        "type IN ('visited', 'wishlist', 'favorite')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_venue_saves_type_allowed", "venue_saves", type_="check")
    # ### end Alembic commands ###
