"""initial

Revision ID: ed922e14b5ac
Revises:
Create Date: 2026-08-13 00:41:21.307779

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ed922e14b5ac"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
