"""add venue discovery enrichment fields

Implements ADR-0009 in obur-docs: `district`, `is_verified`, and the
`status` string replaced by two independent booleans (`is_active`,
`is_suspended`). All prior venues have `status = 'active'`, so dropping
it is lossless: no backfill needed, `is_active`/`is_suspended`'s own
defaults already reproduce that same state.

The partial unique index on `google_places_id` (only over non-NULL
values, so the many venues without one don't collide with each other)
is what makes the exact-match layer of `create_venue`'s duplicate
detection meaningful at all; without it, two venues could carry the
same Google identity.

`venues_select`'s RLS policy (migration `c1d5a8f042e7`) is widened from
`USING (true)` to also exclude suspended venues from anyone but an
admin, the same "hidden must be indistinguishable from nonexistent"
treatment a blocked profile already gets, now enforced at the database
layer too, not just left to the application to remember on every read
path. `is_active` is deliberately not part of this policy: a closed
venue stays visible (shown transparently, per ADR-0009), only
suspension hides it.

`rls_verify_venue_if_eligible`, a `SECURITY DEFINER` function, exists
for one narrow reason: `venues_update` (same prior migration) only
allows an admin to UPDATE a venue, but ADR-0009's auto-verification path
(a `google_places_id` match plus enough independent check-ins) is meant
to fire from an ordinary user's own check-in creation, not an admin
action. Rather than widen `venues_update` generally, this function
encodes exactly the one safe mutation ("flip `is_verified` to true, and
only if the row already qualifies") and nothing else, the same shape
already used for the RLS helper predicates themselves
(`rls_is_owner_or_admin` and friends) that need to see past RLS for
their own narrow lookup. The threshold is passed in rather than
hardcoded here, so `app/services/venue.py`'s constant stays the one
place that number is defined (see `CLAUDE.md`'s migration-isolation
rule: a migration carries its own literal values, but a parameter isn't
one).

Revision ID: f7514fe63beb
Revises: f6a3d857e142
Create Date: 2026-08-25 13:53:24.763710

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7514fe63beb"
down_revision: str | Sequence[str] | None = "f6a3d857e142"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_APP_ROLE_NAME = "obur_app"

_CREATE_VERIFY_VENUE_FUNCTION_SQL = """
    CREATE FUNCTION rls_verify_venue_if_eligible(
        target_venue_id uuid, min_checkins integer
    )
    RETURNS void
    LANGUAGE sql
    SECURITY DEFINER
    SET search_path = public
    AS $$
        UPDATE venues
        SET is_verified = true
        WHERE id = target_venue_id
          AND is_verified = false
          AND google_places_id IS NOT NULL
          AND (
              SELECT COUNT(DISTINCT user_id) FROM checkins
              WHERE checkins.venue_id = target_venue_id
                AND checkins.visibility = 'public'
                AND checkins.deleted_at IS NULL
          ) >= min_checkins;
    $$;
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("venues", sa.Column("district", sa.String(), nullable=True))
    op.add_column(
        "venues",
        sa.Column("is_verified", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "venues",
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
    )
    op.add_column(
        "venues",
        sa.Column("is_suspended", sa.Boolean(), server_default="false", nullable=False),
    )
    op.drop_column("venues", "status")
    # ### end Alembic commands ###

    op.execute(
        """
        CREATE UNIQUE INDEX uq_venues_google_places_id
        ON venues (google_places_id)
        WHERE google_places_id IS NOT NULL
        """
    )
    op.execute(
        """
        ALTER POLICY venues_select ON venues
        USING (rls_is_admin() OR NOT is_suspended)
        """
    )

    op.execute(_CREATE_VERIFY_VENUE_FUNCTION_SQL)
    op.execute(
        "GRANT EXECUTE ON FUNCTION rls_verify_venue_if_eligible(uuid, integer) "
        f"TO {_APP_ROLE_NAME}"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP FUNCTION IF EXISTS rls_verify_venue_if_eligible(uuid, integer)")
    op.execute("ALTER POLICY venues_select ON venues USING (true)")
    op.execute("DROP INDEX IF EXISTS uq_venues_google_places_id")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "venues",
        sa.Column(
            "status",
            sa.VARCHAR(),
            server_default=sa.text("'active'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("venues", "is_suspended")
    op.drop_column("venues", "is_active")
    op.drop_column("venues", "is_verified")
    op.drop_column("venues", "district")
    # ### end Alembic commands ###
