"""Custom exception classes, one module per service domain."""

from app.exceptions.auth_exceptions import (
    AuthError,
    InvalidTokenError,
    InvalidWebhookSignatureError,
)
from app.exceptions.checkin_exceptions import (
    CheckinError,
    CheckinNotFoundError,
    DuplicateProductRatingError,
    EmptyProductListError,
    FutureVisitDateError,
    NotCheckinOwnerError,
    ProductNotAtVenueError,
)
from app.exceptions.social_exceptions import (
    BookmarkNotFoundError,
    CloseFriendNotFoundError,
    DuplicateListItemError,
    FollowNotFoundError,
    LikeNotFoundError,
    ListError,
    ListItemNotFoundError,
    ListNotFoundError,
    NotAFollowerError,
    NotListOwnerError,
    SelfFollowError,
    SocialError,
)
from app.exceptions.venue_exceptions import (
    DuplicateVenueNearbyError,
    GlobalProductTypeNotFoundError,
    NotVenueSaveOwnerError,
    ProductError,
    ProductNotFoundError,
    VenueCategoryNotFoundError,
    VenueError,
    VenueNotFoundError,
    VenueSaveNotFoundError,
)

__all__ = [
    "AuthError",
    "BookmarkNotFoundError",
    "CheckinError",
    "CheckinNotFoundError",
    "CloseFriendNotFoundError",
    "DuplicateListItemError",
    "DuplicateProductRatingError",
    "DuplicateVenueNearbyError",
    "EmptyProductListError",
    "FollowNotFoundError",
    "FutureVisitDateError",
    "GlobalProductTypeNotFoundError",
    "InvalidTokenError",
    "InvalidWebhookSignatureError",
    "LikeNotFoundError",
    "ListError",
    "ListItemNotFoundError",
    "ListNotFoundError",
    "NotAFollowerError",
    "NotCheckinOwnerError",
    "NotListOwnerError",
    "NotVenueSaveOwnerError",
    "ProductError",
    "ProductNotAtVenueError",
    "ProductNotFoundError",
    "SelfFollowError",
    "SocialError",
    "VenueCategoryNotFoundError",
    "VenueError",
    "VenueNotFoundError",
    "VenueSaveNotFoundError",
]
