"""Custom exception classes, one module per service domain."""

from app.exceptions.auth_exceptions import (
    AuthError,
    InvalidTokenError,
    InvalidWebhookSignatureError,
)
from app.exceptions.checkin_exceptions import (
    CheckinError,
    CheckinNotFoundError,
    FutureVisitDateError,
    NotCheckinOwnerError,
)
from app.exceptions.report_exceptions import (
    ContentReportNotFoundError,
    ReportError,
    VenueReportNotFoundError,
)
from app.exceptions.social_exceptions import (
    BlockNotFoundError,
    BookmarkNotFoundError,
    CloseFriendNotFoundError,
    DuplicateListItemError,
    FollowNotFoundError,
    LikeNotFoundError,
    ListError,
    ListItemNotFoundError,
    ListNotFoundError,
    MuteNotFoundError,
    NotAFollowerError,
    NotListOwnerError,
    SelfBlockError,
    SelfFollowError,
    SelfMuteError,
    SocialError,
)
from app.exceptions.user_exceptions import (
    AccountNotFrozenError,
    UserError,
    UsernameChangedTooRecentlyError,
    UsernameTakenError,
    UserNotFoundError,
)
from app.exceptions.venue_exceptions import (
    DuplicateVenueNearbyError,
    NotVenueSaveOwnerError,
    VenueCategoryNotFoundError,
    VenueError,
    VenueNotEligibleForVerificationError,
    VenueNotFoundError,
    VenueSaveNotFoundError,
)

__all__ = [
    "AccountNotFrozenError",
    "AuthError",
    "BlockNotFoundError",
    "BookmarkNotFoundError",
    "CheckinError",
    "CheckinNotFoundError",
    "CloseFriendNotFoundError",
    "ContentReportNotFoundError",
    "DuplicateListItemError",
    "DuplicateVenueNearbyError",
    "FollowNotFoundError",
    "FutureVisitDateError",
    "InvalidTokenError",
    "InvalidWebhookSignatureError",
    "LikeNotFoundError",
    "ListError",
    "ListItemNotFoundError",
    "ListNotFoundError",
    "MuteNotFoundError",
    "NotAFollowerError",
    "NotCheckinOwnerError",
    "NotListOwnerError",
    "NotVenueSaveOwnerError",
    "ReportError",
    "SelfBlockError",
    "SelfFollowError",
    "SelfMuteError",
    "SocialError",
    "UserError",
    "UserNotFoundError",
    "UsernameChangedTooRecentlyError",
    "UsernameTakenError",
    "VenueCategoryNotFoundError",
    "VenueError",
    "VenueNotEligibleForVerificationError",
    "VenueNotFoundError",
    "VenueReportNotFoundError",
    "VenueSaveNotFoundError",
]
